### ISSUE TITLE
Changing the search scope should trigger a new search

### ISSUE THREAD

**Issue by mickeroo** [osulp/primo#10]
In the basic search view, when there is an item in the search keyword box and the scope is changed, the search should be triggered automatically.

For example, if I've searched the Everything scope for "stuff" and I change the scope to At OSU Libraries Only and the search box still has my search term, I'd like the search to execute without having to click the Search button.

**Comment by mickeroo** [comment]
@stefaniebuck001 I've got this working for the OSU_TEST view

http://search.library.oregonstate.edu/primo_library/libweb/action/search.do?vid=OSU_TEST

and so far I've tried it out successfully on Win8/IE10, Chrome, and FF.  Please take a look and let me know if it behaves as expected.

**Comment by stefaniebuck001** [comment]
Hi Mike,

It’s working intermittently. It worked the first few times abut stopped after that.

Stefanie

Stefanie Buck
Ecampus and Instructional Design Librarian
121 Valley Library
Oregon State University
Corvallis, OR 97331
(541) 737-7273
stefanie.buck@oregonstate.edu

**Comment by stefaniebuck001** [comment]
Never mind. I was not clicking on the scope name. Now it’s working.

Stefanie Buck
Ecampus and Instructional Design Librarian
121 Valley Library
Oregon State University
Corvallis, OR 97331
(541) 737-7273
stefanie.buck@oregonstate.edu
