### ISSUE TITLE
Ejournals list/permalink pushed to the left

### ISSUE THREAD

**Issue by mickeroo** [osulp/primo#16]

**Comment by mickeroo** [comment]
![screen shot 2015-05-01 at 2 17 01 pm](https://cloud.githubusercontent.com/assets/2022754/7437510/ce6f9918-f00c-11e4-9087-38499d668af6.png)

**Comment by straleyb** [comment]
@mickeroo @luisgreg99 @stefaniebuck001 I believe this one is solved by #29 as well. Can someone confirm?
