### ISSUE TITLE
OSU Test logo

### ISSUE THREAD

**Issue by mickeroo** [osulp/primo#19]
Change the OSU logo in this screen so that we know that it's the test view

**Comment by stefaniebuck001** [comment]
![osu_logo_test](https://cloud.githubusercontent.com/assets/11510167/7438524/5cbe3e06-f01a-11e4-94a5-827cf86a6967.png)

**Comment by mickeroo** [comment]
This is now live in production Primo:

http://search.library.oregonstate.edu/primo_library/libweb/action/search.do?vid=OSU_TEST
