### ISSUE TITLE
Make the services view look like the main view

### ISSUE THREAD

**Issue by mickeroo** [osulp/primo#24]
The services view should be customized so that t looks like the rest of the Primo views.

When you click on an item the view that displays- services vice-  has no headers, etc. We need to change the layout so it looks like other Primo views.  Probably missing headercontainer views, footer, etc.

**Comment by straleyb** [comment]
Waiting on this until later.

**Comment by mickeroo** [comment]
For example, here is an article in Academic Search Premier.
![unknown-2](https://cloud.githubusercontent.com/assets/2022754/7464648/7124877c-f279-11e4-8a16-93726449114c.jpeg)

If you click on the FindIt@OSU button, it takes you back to Primo and looks like this
![unknown-1](https://cloud.githubusercontent.com/assets/2022754/7464642/670b090a-f279-11e4-8c12-450c8e91d9dd.jpeg)

If you view the same record in Primo (just searching for the title), it looks like this:
![unknown](https://cloud.githubusercontent.com/assets/2022754/7464639/5f5848e4-f279-11e4-830d-8cbfb759af39.jpeg)

We’d like them both to look like the lower example.

**Comment by straleyb** [comment]
We need these to have a header and footer in that page instead just an empty page with nothing at all.

EDIT: Only happens on OSU_TEST @mickeroo

**Comment by straleyb** [comment]
@mickeroo Is this solved?

**Comment by mickeroo** [comment]
No, this is a different view that I think I can fix in the Back Office.

**Comment by straleyb** [comment]
Ok, I was trying to look for the page that did this and couldnt. hehe.

**Comment by mickeroo** [comment]
**Steps to repeat (STR):**
1. Go here: http://osulibrary.oregonstate.edu/research-databases
2. click on Academic Search Premier
3. enter a search term: e.g. "stuff"
4. click the "FindIt@OSU" link
5. this is the page.

It's missing a header and footer so we just need to add it to the layout in PBO

**Comment by mickeroo** [comment]
The header and footer were set up in the Static HTML tile, but we also needed to add in the main menu links (see https://github.com/osulp/primo/issues/42 for details) **and** add all of the search scopes and tabs from the OSU view to the osu_services_view.
