### ISSUE TITLE
Add Main Menu links on Services view

### ISSUE THREAD

**Issue by stefaniebuck001** [osulp/primo#42]
When you're on the services page (coming from a database), the main menu disappears. It's kind of annoying. Can that be added?

**Comment by mickeroo** [comment]
To do this, you have to go into the Tiles Configuration for the view and select the "Home Page" page.  Then click the Edit Tile button next to the Main Menu tile. On the next screen you can add all of the labels for the menu items you want.  In this case I copied all of the labels and links from the OSU view.  Then save, and deploy.

This is live on the production site's services view.
