### ISSUE TITLE
Remove similar articles tab

### ISSUE THREAD

**Issue by stefaniebuck001** [osulp/primo#43]
The Similar articles tab is showing up again after it was hidden in the css.

**Comment by stefaniebuck001** [comment]
![similar articles](https://cloud.githubusercontent.com/assets/11510167/8855771/dd8e6852-311b-11e5-9847-8499d03b5dde.png)

**Comment by wickr** [comment]
I don't think this was ever hidden by CSS before, I can't find "RecommendTab" or "Similar Articles" in either CSS file. Should be addable though. Unless there's some other toggle setting in the Primo Back Office.

**Comment by mickeroo** [comment]
@stefaniebuck001 I'm not able to reproduce the appearance of this tab.  Is it something you fixed in the PBO?

![screen shot 2015-07-29 at 4 48 22 pm](https://cloud.githubusercontent.com/assets/2022754/8972759/c9875e68-3611-11e5-923e-5bb4500a8b07.png)

**Comment by stefaniebuck001** [comment]
I did this in the mapping tables.
