### ISSUE TITLE
Advanced Search link on home page going to course reserves tab

### ISSUE THREAD

**Issue by stefaniebuck001** [osulp/primo#45]
When you click on the Advanced Search link on the home page, it goes to the course reserve tab, not the advanced search tab. 

Right now the URL goes to tab=cr_tab and it should point to tab=default_tab

**Comment by stefaniebuck001** [comment]
Nope, still going to course reserves.

**Comment by mickeroo** [comment]
The change hasn't been pushed to the server yet.

**Comment by stefaniebuck001** [comment]
Oh. Sorry. Jumped the gun.

Stefanie Buck
Ecampus and Instructional Design Librarian
121 Valley Library
Oregon State University
Corvallis, OR 97331
(541) 737-7273
stefanie.buck@oregonstate.edu

**Comment by mickeroo** [comment]
Git does us a favor of closing a ticket if we mention it in the notes and the corresponding pull request is closed, but sometimes that doesn't mean that it's ACTUALLY closed- e.g. live- so we need to figure out a way to be better about that.

The change is live now.
